name: build_and_release
on: [push]
jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install openscad
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: winget install --accept-source-agreements --id=OpenSCAD.OpenSCAD -e
      if: ${{ matrix.os == 'windows-latest' }}
    - run: echo "%ProgramFiles%\OpenSCAD" >> $GITHUB_PATH
      if: ${{ matrix.os == 'windows-latest' }}
    - run: brew install --cask openscad
      if: ${{ matrix.os == 'macos-latest' }}
    - run: make
