name: build_and_release
on: [push]
jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: sudo apt-get install openscad libftdi1-dev
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: winget install --accept-source-agreements --id=OpenSCAD.OpenSCAD -e
      if: ${{ matrix.os == 'windows-latest' }}
    - run: vcpkg install libftdi:x64-mingw-static
      if: ${{ matrix.os == 'windows-latest' }}
    - run: echo "$Env:ProgramFiles\OpenSCAD" >> $Env:GITHUB_PATH
      if: ${{ matrix.os == 'windows-latest' }}
    - run: brew install --cask openscad
      if: ${{ matrix.os == 'macos-latest' }}
    - run: brew install libftdi
      if: ${{ matrix.os == 'macos-latest' }}
    - run: make
      env:
        C_INCLUDE_PATH: C:/vcpkg/packages/libftdi_x64-mingw-static/include
      if: ${{ matrix.os == 'windows-latest' }}
    - run: make
      if: ${{ matrix.os != 'windows-latest' }}
